
[env]
TERM = "xterm-256color"

[font]
size = 13
normal = { family = "Terminess Nerd Font" }

[window]
decorations = "Buttonless"

[window.dimensions]
columns = 80
lines = 26

[keyboard]
bindings = [
  { mods = "Command", key = "P", chars = '\p' },
  { mods = "Command", key = "O", chars = '\o' },
  { mods = "Command", key = "F", chars = '\f' },
  { mods = "Command", key = "Period", chars = " ca" },
  { mods = "Control", key = "Period", chars = " ca" },
  { mods = "Command|Shift", key = "A", chars = "\\\u001B[65;1u" },
]

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
