[common.link]
".gitconfig" = ['~/.gitconfig', "common/.gitconfig"]
"starship.toml" = ['~/.config/starship.toml', "common/starship.toml"]

[unix.link]
nvim = ['~/.config/nvim', "common/nvim"]
".zshrc" = ["~/.zshrc", "unix/.zshrc"]
tmux = ["~/.config/tmux/tmux.conf", "unix/tmux/tmux.conf"]
bat = ["~/.config/bat", "common/bat"]

["unix.gui".link]
alacritty = ["~/.config/alacritty", "unix.gui/alacritty"]
ghostty = ["~/.config/ghostty", "unix.gui/ghostty"]

[linux.link]
"gnome-shell.extensions" = [
  "~/.local/share/gnome-shell/extensions",
  "linux/gnome-shell/extensions",
]
fonts = ["~/.local/share/fonts", "linux/fonts"]
themes = ["~/.themes", "linux/.themes"]

[windows.link]
nvim = ['~/AppData/Local/nvim', "common/nvim"]
wezterm = ['~/.config/wezterm', "windows/wezterm"]
PowerToys = ['~/Documents/PowerToys', "windows/PowerToys"]
PowerShell_profile = [
  '~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1',
  "windows/PowerShell/Microsoft.PowerShell_profile.ps1",
]
bat = ["~/AppData/Roaming/bat", "common/bat"]
nushell = ["~/AppData/Roaming/nushell", "windows/nushell"]

[android.link]
".termux" = ["~/.termux", "android/.termux"]
